### ISSUE TITLE
oddsRatio enhancements

### ISSUE THREAD

**Issue by bumbanian** [SPATIAL-Lab/isorig#13]
1) for polygons make sure values reported and used are sums of grid cell probabilities, not means
2) improve annotation of results...

instead of "mean.1.1" write "P1"
also e.g.
"P1/P2"

It's unclear to me what all the "ratio to max" values represent. I don't think it makes sense to include more than the ratio of cell 1 to the max and the ratio of cell 2 to the max and the ratio of the max to min. (P1/Pmax, P2/Pmax, Pmin/Pmax)

**Comment by bumbanian** [comment]
ALSO - implement method for SpatialPoints object

**Comment by Demerara** [comment]
Done

**Comment by bumbanian** [comment]
What about #1 above? Is sum or mean being used? Current output:

$`P1/P2_odds_ratio`
    mean.1.1     mean.2.1     mean.1.2     mean.2.2 
1.034392e-03 1.259731e-04 1.616890e-07 3.477951e-05 

$`ratio of numbers of cells in two polygons`
[1] 1

Not clear that annotation has been updated for polygons

**Comment by bumbanian** [comment]
> oddsRatio(asn, p12)
$`P1/P2_odds_ratio`
        A         B         C         D 
0.7419021 0.4672213 0.2911667 1.7671187 

$`ratio of numbers of cells in two polygons`
[1] 1

This annotation is still not helpful...what are A, B, C, D?

**Comment by bumbanian** [comment]
OK, looks good
