### ISSUE TITLE
subset data fails

### ISSUE THREAD

**Issue by bumbanian** [SPATIAL-Lab/isorig#19]
fails when using mask (naMap)

> d = subOrigData(taxon = c("Homo sapiens"), mask = naMap)
Error in validObject(.Object) : 
  invalid class “SpatialPointsDataFrame” object: invalid object for slot "data" in class "SpatialPointsDataFrame": got class "SpatialPointsDataFrame", should be or extend class "data.frame"

**Comment by Demerara** [comment]
Fixed.
Please reinstall the package from Github to update this function.

**Comment by bumbanian** [comment]
Still fails, new error.

> d = subOrigData(taxon = c("Homo sapiens"), mask = naMap)
Error: identicalCRS(x, y) is not TRUE

Also Rmarkdown upload to GitHub is inconvenient, no easy way to open this large file from the GitHub website…

Gabe

**Comment by Demerara** [comment]
Fixed. 
This bug is resulted from that knownOrig was not assigned with CRS.
